### ISSUE TITLE
Parser does not respect xml encoding.

### ISSUE THREAD

**Issue by Gonzih** [scsibug/feedparser-clj#9]
Hi, I'm using your amazing lib in my feeds2imap.clj project. Recently one person reported issue with this feed http://ibash.org.ru/rss.xml. Looks like feed is using windows-1251 encoding (which is horrible), but still. Is there any way to make parser respect encoding specified in xml and convert everything to unicode?

Thanks!

**Comment by fifigyuri** [comment]
I have the same issue with another feed, http://www.hirek.sk/rss/hirek.xml. What do you suggest, how to put the source into the proper encoding? Does feedparser-clj has a support for that or should an other lib used for preprocessing?

**Comment by Gonzih** [comment]
no, feedparser-clj does not do anything. I can try to fetch data on my 
own and maybe try to detect encoding and then convert it to unicode. I'm 
still surprised that there are websites not using unicode. I will take a 
look at that once I have some spare time. Thanks for providing another 
example.

**Comment by fifigyuri** [comment]
I'm also surprised, but that's reality. I checked the referred java libraries and it seems only few encodings, ascii, utf-8, utf-16,... are supported.

Maybe it's not feedparser-clj's job to do the conversion. Maybe a recommendation about how to pre-process the feeds is sufficient. Probably for most of the feedparser-clj user unicode is enough.

What would you recommend, what to use to do the conversion?

**Comment by Gonzih** [comment]
I would say java interop can do the trick.

**Comment by fifigyuri** [comment]
which java to interop with? :) which library, do you know some resource/document where the encoding conversion is documented?

**Comment by Gonzih** [comment]
http://stackoverflow.com/questions/5729806/encode-string-to-utf-8
